### PR TITLE
#8 Improve UI

### LINKED ISSUE #7: Creating a Logo for URL-shortener
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request

**Current behavior:**
Currently we don't have any logo for our website

**Expected behavior:**
We will be having this Logo in our navigation bar
logo

 I would like to merge this logo with navigation bar.

### LINKED ISSUE #8: Improve UI
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request

**Current behavior:**

Current Page design Doesn't have any Navigation Bar

**Expected behavior:**

Projecting Navigation bar for User along with the URL-Accepting-Text field and button
imagedash

### PR DESCRIPTION
**Pull request by rahulkumar082**
Fixes #7 and  #8 Improve UI

#### Checklist

- [x] I have read the CONTRIBUTING guidelines and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works 
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
UI design for taking input from the user as well as Navigation bar for them
#### Changes proposed in this pull request:
Working for the desired output field also
-
-
-

### CODE REVIEW

**Comment by zamhaq** [comment]
@rahulkumar082 please look and fix the conflicts.

**Comment by Logan1x** [comment]
I agree with @zamhaq, an open source project/code should be more readable and should be easier to understand to new contributor's and by looking at your code I can say it will confuse them as a beginner.

**Comment by rahulkumar082** [comment]
Thanks @Logan1x  I will try to improvise the readability of my code.

**Comment by rahulkumar082** [comment]
Hey @zamhaq , I have made some changes to resolve the previous conflicts , please look into it .
Thank you :+1:

**Comment by ShikharJ** [comment]
Ping @zamhaq.

**Pull request merged**
